name: build and push to ECR

on:
    push:
        branches: ['main']
    #pull_requests:
    #  branches: [ 'main','dev' ]

jobs:
    build_scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: trivy Scan
              run: trivy fs .


